# Generated by Django 3.1 on 2020-09-26 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_email', models.EmailField(max_length=32, null=True)),
                ('profile_telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_country', models.CharField(blank=True, max_length=40, null=True)),
                ('profile_county', models.CharField(blank=True, max_length=40, null=True)),
                ('profile_address_1', models.CharField(blank=True, max_length=300, null=True)),
                ('profile_address_2', models.CharField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
