# Generated by Django 3.1 on 2020-09-29 13:26

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpage',
            old_name='profile_address_1',
            new_name='Primary_address_1',
        ),
        migrations.RenameField(
            model_name='userpage',
            old_name='profile_address_2',
            new_name='Primary_address_2',
        ),
        migrations.RenameField(
            model_name='userpage',
            old_name='profile_email',
            new_name='Primary_email',
        ),
        migrations.RenameField(
            model_name='userpage',
            old_name='profile_telephone',
            new_name='Primary_telephone',
        ),
        migrations.RemoveField(
            model_name='userpage',
            name='profile_country',
        ),
        migrations.AddField(
            model_name='userpage',
            name='Primary_country',
            field=django_countries.fields.CountryField(blank=True, max_length=40, null=True),
        ),
    ]
