# Generated by Django 3.1 on 2020-09-15 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.cartitems')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('email', models.CharField(editable=False, max_length=32)),
                ('telephone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=40)),
                ('county', models.CharField(max_length=40)),
                ('address_1', models.CharField(max_length=4)),
                ('address_2', models.CharField(max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('grand_totla', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('items', models.ManyToManyField(to='checkout.OrderItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
