# Generated by Django 3.1 on 2020-09-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_1',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='address_2',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=32),
        ),
    ]
