# Generated by Django 3.1 on 2020-09-30 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20200929_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_total',
        ),
    ]
