# Generated by Django 3.1 on 2020-09-14 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200907_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
