# Generated by Django 3.1 on 2020-09-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(choices=[('500g', 0.5), ('1kg', 1), ('1.5kg', 1.5), ('2kg', 2)], decimal_places=2, default=0.5, max_digits=6),
        ),
    ]
