# Generated by Django 3.1 on 2020-09-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_products_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.DecimalField(choices=[(1, '1kg'), (0.5, '500g'), (2, '2kg'), (1.5, '1.5kg')], decimal_places=2, default=0.5, max_digits=6),
        ),
    ]
